version: "2"

run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    text:
      path: stdout
  sort-results: true

linters:
  disable-all: true
  enable:
    # Correctness / reliability
    - staticcheck
    - govet
    - errcheck
    - errchkjson
    - errorlint
    - nilerr
    - nilnil
    - bodyclose
    - durationcheck

    # Maintainability / complexity limits
    - gocyclo
    - gocognit
    - funlen
    - nestif
    - dupl

    # Readability / consistency
    - revive
    - misspell
    - whitespace
    - unconvert
    - unparam
    - unused
    - ineffassign
    - wastedassign
    - predeclared
    - prealloc
    - makezero
    - usestdlibvars
    - asciicheck
    - bidichk
    - nolintlint

    # Team-specific rules via ruleguard
    - gocritic
    - gosec

  settings:
    govet:
      # Strict by default: correctness > convenience.
      enable-all: true
      # High-churn / low-signal in practice unless you commit to struct padding work.
      disable:
        - fieldalignment

    errcheck:
      check-type-assertions: true
      check-blank: true

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    funlen:
      lines: 80
      statements: 50

    nestif:
      min-complexity: 3

    dupl:
      threshold: 100

    misspell:
      locale: US

    nolintlint:
      require-explanation: true
      require-specific: true
      allow-leading-space: false

    revive:
      severity: warning
      confidence: 0.8
      error-code: 0
      warning-code: 0
      rules:
        # --- Correctness / reliability ---
        - name: atomic
        - name: datarace
        - name: waitgroup-by-value
        - name: range-val-in-closure
        - name: range-val-address
        - name: unreachable-code

        # --- Error handling discipline (North Star: loud failures) ---
        - name: unhandled-error
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: errorf

        # --- Readability / simplicity ---
        - name: indent-error-flow
        - name: superfluous-else
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: bool-literal-in-expr
        - name: string-format
        - name: unnecessary-stmt
        - name: unnecessary-format

        # --- Public surfaces must be documented (North Star: public API docblocks) ---
        # Team decision: disable exported/package-comments rules; rely on review for meaningful comments.
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

        # --- Naming policy ---
        # Team-defined expectations: keep only a tiny allowlist of conventional short names.
        # NOTE: this does not govern receiver names; receiver names are enforced by ruleguard.
        - name: var-naming
          arguments:
            - - ID
              - URL
              - HTTP
              - JSON
              - SHA1
              - ctx
              - err
              - cfg
              - cmd
              - t
              - tt
              - fs
            - - i
              - j
              - k
              - v

        # Keep receiver naming enabled for baseline consistency, but the hard rule is ruleguard.
        - name: receiver-naming

        # --- Boundary / context usage ---
        - name: context-as-argument
        - name: context-keys-type
        - name: flag-parameter

        # --- Complexity thresholds (match .golangci.yml) ---
        - name: cyclomatic
          arguments: [15]
        - name: cognitive-complexity
          arguments: [20]
        - name: function-length
          arguments: [80, 50]
        - name: argument-limit
          arguments: [8]
        - name: function-result-limit
          arguments: [3]

        # --- Import hygiene ---
        - name: blank-imports
        - name: dot-imports
        - name: duplicated-imports
        - name: redundant-import-alias

        # --- General maintainability ---
        - name: confusing-naming
        - name: confusing-results
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: unexported-return
        - name: redefines-builtin-id

    gocritic:
      disable-all: true
      enabled-checks:
        # Required: ruleguard for custom team rules.
        - ruleguard

        # Required: high-signal correctness/robustness checks.
        - exitAfterDefer
        - emptyStringTest
        - equalFold
        - filepathJoin
        - httpNoBody
        - offBy1
        - sloppyLen
        - sloppyTypeAssert

      settings:
        ruleguard:
          failOn: dsl,import
          rules: '${config-path}/ruleguard/rules-team.go'
          enable: receiverNameMinLength,forbidIgnoringJSONDecodeError,forbidIgnoringHTTPRequestBuildError,forbidIgnoringAtoiErrorInBoundaryParsing

    gosec:
      exclude-generated: true
      severity: low
      confidence: low
      excludes:
        # SHA1 is required by the mod ecosystem for fingerprinting/hashes.
        - G401
        - G505
      config:
        global:
          nosec: false
          show-ignored: true
          audit: true
        G101:
          pattern: "(?i)passwd|password|pwd|secret|private_key|token|api[_-]?key|bearer|cred"
          ignore_entropy: false
          entropy_threshold: "80.0"
          per_char_threshold: "3.0"
          truncate: "32"
        # Policy: MMM does not treat config/lock/mod artifacts as secret-bearing.
        # Keep permissions compatible with shared setups while avoiding overly permissive modes.
        G301: "0755"
        G302: "0644"
        G306: "0644"

  exclusions:
    # Keep the v1 default behavior for generated files.
    generated: lax

    # Do not silently hide issues via default exclude presets.
    presets: []

    # v1 exclude-dirs-use-default: vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
    paths:
      - vendor$
      - third_party$
      - testdata$
      - examples$
      - Godeps$
      - builtin$

    rules:
      - path: _test\.go
        linters:
          - dupl
      - path: _test\.go
        linters:
          - errcheck
      - path: _test\.go
        linters:
          - funlen
      - path: _test\.go
        linters:
          - gocognit
      - path: _test\.go
        linters:
          - unparam
      - path: _test\.go
        linters:
          - prealloc
      - path: _test\.go
        linters:
          - misspell
      - path: _test\.go
        linters:
          - whitespace
      - path: _test\.go
        linters:
          - unused
      - path: _test\.go
        linters:
          - revive
        text: "unused-parameter"
      - path: _test\.go
        linters:
          - revive
        text: "package-comments"
      - path: _test\.go
        linters:
          - gocritic
        text: "httpNoBody"

formatters:
  exclusions:
    paths:
      - vendor$
      - third_party$
      - testdata$
      - examples$
      - Godeps$
      - builtin$

issues:
  # Do not truncate.
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
